syncromatics/syncromatics-track-api

- src/examples/get_routes.test.js
- src/mocks.js
- src/resources/Customer.js
- src/resources/Customer.test.js
- src/resources/Route.js
- src/resources/Route.test.js
- src/resources/RoutesContext.js
- src/resources/RoutesContext.test.js
- src/resources/VehiclesContext.js
Just learned I can't retarget a PR after its been created in GitHub
> feat(routes): Added support for getting routes for a customer (EN-1531)

- src/examples/get_stops.test.js
- src/mocks.js
- src/resources/Customer.js
- src/resources/Customer.test.js
- src/resources/Stop.js
- src/resources/Stop.test.js
- src/resources/StopsContext.js
- src/resources/StopsContext.test.js
- src/resources/Vehicle.js
Also included comment updates for `Sign` and `Vehicle`.
> feat(stops): Add support for getting stops for a customer (EN-1527)

- src/examples/get_tags.test.js
- src/mocks.js
- src/resources/Customer.js
- src/resources/Customer.test.js
- src/resources/MessageTemplate.js
- src/resources/SignMessage.js
- src/resources/Tag.js
- src/resources/Tag.test.js
- src/resources/TagsContext.js
- src/resources/TagsContext.test.js
This code isn't technically usable since we haven't deployed the Signs API stuff yet
> Tags API client

- src/examples/get_message_templates.test.js
- src/mocks.js
- src/resources/Customer.js
- src/resources/MessageTemplate.js
- src/resources/MessageTemplate.test.js
- src/resources/Tag.js
- src/resources/Tag.test.js
Creation and updating for message template
> Added create and update for message template

- src/Client.js
- src/Client.test.js
- src/mocks.js
- src/resources/MessageTemplate.js
- src/resources/Page.test.js
- src/resources/Tag.js
- src/resources/index.test.js
- src/testutils.js
Saw that requests were `[object Object]` instead of stringified JSON. This should fix this. I moved the `toBlob` test util function into a static on `Client`.
> fix(client): Fixed issue with requesting JavaScript objects via fetch()

- src/resources/Page.js
- src/resources/PagedContext.js
Keeping these in sync since documentation is auto-generated from comments
> Catch comments up with changes parameter casing

- src/examples/get_agency.test.js
- src/mocks.js
- src/resources/Agency.js
- src/resources/Agency.test.js
- src/resources/Customer.js
- src/resources/Customer.test.js
- src/resources/index.test.js
Support retrieving and updating the single agency resource per customer.
> Add Agency resource to customer

- src/examples/get_drivers.test.js
- src/examples/get_run.test.js
- src/examples/get_trip.test.js
- src/mocks.js
- src/resources/Customer.js
- src/resources/Customer.test.js
- src/resources/Driver.js
- src/resources/Driver.test.js
- src/resources/DriversContext.js
- src/resources/DriversContext.test.js
- src/resources/Run.js
- src/resources/Run.test.js
- src/resources/Trip.js
- src/resources/Trip.test.js
* Add `Driver` resource.
* Add `DriversContext` resource for querying drivers.
* Add `Trip` resource.
* Add `Run` resource.
> feat(driver-run-trip): Add support for Drivers, Runs, Trips.

- src/examples/get_block.test.js
- src/mocks.js
- src/resources/Block.js
- src/resources/Block.test.js
- src/resources/Customer.js
- src/resources/Customer.test.js
- src/resources/Service.js
- src/resources/Trip.js
* Add support for Block resource
* Update Trip mocks to better match data model with singular run
> EN-1310: Add block resource

- README.md
Quick pointer to examples dir in readme
> Update README to point users towards examples directory.

- package-lock.json
- src/mocks.js
- src/resources/index.js
- src/resources/index.test.js
And add legacy support for expiration date in milliseconds.
> fix(client): Ensure required Accept header is sent

- src/resources/RealTimeContext.js
> fix(docs): Update JSDoc comments for realtime subscriptions

- package-lock.json
- src/examples/subscribe_stops.test.js
- src/mocks/realTime.js
- src/resources/RealTimeContextFactory.js
- src/resources/StopsRealTimeContext.js
- src/resources/StopsRealTimeContext.test.js
Includes updated package-lock file.
> feat(stops): EN-3047: Added stops real time support

- src/examples/get_patterns.test.js
- src/examples/get_voip_ticket.test.js
- src/mocks/patterns.js
- src/resources/PatternsContext.js
- src/resources/Settings.test.js
patch(voip): Clean compiler warnings
> feat(patterns): Search for patterns by active date and enabled.

- package-lock.json
- src/examples/get_area.test.js
- src/mocks/areas.js
- src/mocks/index.js
- src/mocks/realTime.js
- src/resources/Area.js
- src/resources/Area.test.js
- src/resources/AreasContext.js
- src/resources/AreasContext.test.js
- src/resources/AreasRealTimeContext.js
- src/resources/AreasRealTimeContext.test.js
- src/resources/Customer.js
- src/resources/Customer.test.js
- src/resources/RealTimeContextFactory.js
- src/resources/RealTimeContextFactory.test.js
- feat(areas): Support REST API for customer areas 
- feat(areas): Support real-time API for customer areas
> EN-3989: Add support for customer Areas

- src/resources/PatternsContext.js
Allows users to send a date string to WithAsOf function of patterns context for more compatibility with specific times.
> feat(patternsAsOf): Add support for date strings in WithAsOf function

- src/RealTimeClient.js
Commit 28bf0d introduced a feature where active subscriptions made via the
real-time client would resubscribe upon a disconnect and reconnect.
This could pose a problem if Track API was having errors connecting to its
backing services, because the client might get into a state where only some of
the subscriptions it tries to restart will actually restart.  Then, on the next
disconnect/reconnect, it will only restart the ones that started successfully.
This PR makes sure that subscriptions that were pending at the time of the
disconnect are also restarted.
> fix(reconnect): Also reconnect pending connections.

- src/resources/Sign.js
- src/resources/Sign.test.js
> fix(signs): Fix sign update patch call.

- src/mocks/incidents.js
- src/mocks/index.js
- src/resources/Incident.js
- src/resources/Incident.test.js
feat(incident): EN-6210 Update sync JS api for emergency actions
* Add incident resource
* Add unit test and mocks
> feat(incident): EN-6210 Update sync JS api for emergency actions

- src/examples/subscribe_incidents.test.js
- src/mocks/realTime.js
- src/resources/IncidentsRealTimeContext.js
- src/resources/IncidentsRealTimeContext.test.js
- src/resources/RealTimeContextFactory.js
- src/resources/RealTimeContextFactory.test.js
* Add Realtime incident Context and related text
> feat(incident): EN-5351: Subscribe to Incidents heartbeats

- .travis.yml
- package-lock.json
- package.json
revert semantic version to 6.3.2
> revert semantic version to 6.3.2

- src/examples/manage_twitter_authentication.test.js
- src/mocks/index.js
- src/mocks/twitter.js
- src/resources/Customer.js
- src/resources/Customer.test.js
- src/resources/TwitterOAuth.js
- src/resources/TwitterOAuth.test.js
- src/resources/TwitterUsername.js
- src/resources/TwitterUsername.test.js
* Add functionality to save Twitter OAuth tokens.
* Add functionality to retrieve connected Twitter usernames.
> feat(twitter): EN-6897: Add Twitter features.

- src/examples/manage_twitter_authentication.test.js
- src/mocks/index.js
- src/mocks/twitterOAuthRequests.js
- src/resources/Customer.js
- src/resources/Customer.test.js
- src/resources/TwitterOAuthRequest.js
- src/resources/TwitterOAuthRequest.test.js
> feat(twitter): Add support for twitter OAuth requests.

- src/examples/get_asset.test.js
- src/mocks/assets.js
- src/mocks/index.js
- src/resources/Asset.js
- src/resources/Asset.test.js
- src/resources/AssetsContext.js
- src/resources/AssetsContext.test.js
- src/resources/Customer.js
- src/resources/Customer.test.js
> feat(assets): EN-7240: Add Customer Asset support.

- src/resources/AssetsContext.js
> fix(assets): Allow querying for a specific asset type

- src/resources/VoipHeartbeatHandler.js
- Fixed typo in variable names
- Formatting updates by prettier-on-save
> feat(voip): EN-6884: Support participant type in heartbeats
